version: 2
updates:
  # Configuration to update Java / Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"

  # Configuration to keep GitHub Actions workflows up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
